version: '3.7'
services:
    api-gateway-service:
      image: kaushal1998/mmv2-api-gateway-service:0.0.1-SNAPSHOT
      mem_limit: 700m
      ports:
        - "8765:8765"
      networks:
        - currency-networks
      depends_on:
        - eureka-naming-service
        - rabbitmq
      environment:
        eureka.client.serviceUrl.defaultZone: http://eureka-naming-service:8761/eureka
        spring.zipkin.baseUrl: http://zipkin-server:9411
        spring.zipkin.sender.type: rabbit
        rabbit.uri: amqp://guest:guest@rabbitmq:5672
        spring.rabbitmq.host: rabbitmq
    currency-conversionc-service:
      image : kaushal1998/mmv2-currency-conversionc-service:0.0.1-SNAPSHOT
      mem_limit: 700m
      ports:
        - "8100:8100"
      networks:
        - currency-networks
      depends_on:
        - eureka-naming-service
        - rabbitmq
      environment:
        eureka.client.serviceUrl.defaultZone: http://eureka-naming-service:8761/eureka
        spring.zipkin.baseUrl: http://zipkin-server:9411
        spring.zipkin.sender.type: rabbit
        rabbit.uri: amqp://guest:guest@rabbitmq:5672
        spring.rabbitmq.host: rabbitmq
    currency-exchange-service:
      image: kaushal1998/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
      mem_limit: 700m 
      ports:
        - "8000:8000"
      networks:
        - currency-networks
      depends_on:
        - eureka-naming-service
        - rabbitmq
      environment:
        eureka.client.serviceUrl.defaultZone: http://eureka-naming-service:8761/eureka
        spring.zipkin.baseUrl: http://zipkin-server:9411
        spring.zipkin.sender.type: rabbit
        rabbit.uri: amqp://guest:guest@rabbitmq:5672
        spring.rabbitmq.host: rabbitmq
    zipkin-server:
      image: openzipkin/zipkin:latest
      mem_limit: 300m
      ports:
        - "9411:9411"
      networks:
        - currency-networks
      depends_on:
        - rabbitmq
      environment:
        rabbit.uri: amqp://guest:guest@rabbitmq:5672
    rabbitmq:
      image: rabbitmq:3.10.1-management
      ports:
        - "5672:5672"
        - "15672:15672"
      mem_limit: 300m
      networks:
        - currency-networks
    eureka-naming-service:
      image: kaushal1998/mmv2-eureka-naming-service:0.0.1-SNAPSHOT
      mem_limit: 700m
      ports:
        - "8761:8761"
      networks:
        - currency-networks
networks:
    currency-networks:
